import { atom } from "recoil";

export const popularCities = [
  { label: "Москва", value: 599 },
  { label: "Санкт-Петербург", value: 820 },
  { label: "Волгоград", value: 168 },
  { label: "Владивосток", value: 165 },
  { label: "Воронеж", value: 181 },
  { label: "Екатеринбург", value: 273 },
  { label: "Казань", value: 350 },
  { label: "Калининград", value: 354 },
  { label: "Краснодар", value: 461 },
  { label: "Красноярск", value: 472 },
  { label: "Нижний Новгород", value: 643 },
  { label: "Новосибирск", value: 667 },
  { label: "Омск", value: 703 },
  { label: "Пермь", value: 735 },
  { label: "Ростов-на-Дону", value: 801 },
  { label: "Самара", value: 819 },
  { label: "Уфа", value: 1005 },
  { label: "Хабаровск", value: 1015 },
  { label: "Челябинск", value: 1038 },
  { label: "Севастополь", value: 837 },
  { label: "Симферополь", value: 861 },
];

const _ = atom({
  key: "mainStorage",
  default: {
    isDesktop: false,
    platform: "",
    snackbar: "",
    onBoarding: true,
    initData: null,
    citizenshipsData: [{ value: 1, label: "Россия" }],
    citiesData: popularCities,
    placeData: null,
    marksData: null,
    nearestData: null,
    photo: null,
    stateCoords: [],
    changeProfile: false,
    modalState: 1,
    theme: "light",
    selectedVacancyData: null,
    simillarPointsData: null,
    showPageHeader: "",
    favouriteJobs: null,
    listSelectState: 1,
    appType: null,
    dataforpatch: null,
    tgWindowOpened: false,
    readyToUse: false,
    registerPhone: false,
    zoom: 12,
    replyHandler: false,
    lastGeoLocation: null,
    clickedLocation: false,
    savedPhone: null,
    listPlacemarks: null,
    listInitDataHandler: false,
    mockMarks: null,
    tabbarHidden: false,
    sentPhone: null,
    authFirst: false,
    afterLogin: false,
    currentTab: "",
    currentView: null,
    savedMarks: null,
    filterCity: null,
    filterWorkPlace: null,
    filterJob: null,
    mapFilterQuery: null,
    listCityLabel: null,
    clubData: null,
    listCities: null,
    selectedCity: null,
    employers: [],
    filterEmployer: null,
    afterClickPlacemark: false,
    mapData: null,
    afterClickList: false,
    selectedLanguage: "ru",
    selectedVacancyForEdit: null,
    filterEmployersData: [],
    filterVacanciesData: [],
    updateFilters: false,
    salaryFilter: "",
    salaryFilterMax: "",
    notificationsData: null,
    dropdownOpened: false,
    filterCities: null,
    afterSelectingCity: false,
    firstLoad: false,
  },
});

export default _;
